### ISSUE TITLE
fix: docs throw 404

### ISSUE THREAD

**Issue by Minecon724** [spotify-web-api-java/spotify-web-api-java#312] opened 2022-10-25 19:04 UTC
trying to search returns a 404
which is definitely not what i was looking for

**Comment by dargmuesli** [comment] 2022-10-25 19:32
I faced this issue once too, but cannot reproduce it right now. Do you have a specific search query that causes this behavior?

**Comment by Minecon724** [comment] 2022-10-25 19:39
> I faced this issue once too, but cannot reproduce it right now. Do you have a specific search query that causes this behavior?

click on any class

**Comment by Minecon724** [comment] 2022-10-25 20:08
theres a random "undefined" inserted into the url

**Comment by dargmuesli** [comment] 2022-10-25 20:26
Should be fixed now with a98b2952d0d85b9b6b2ddd5d3c8555a7e7815abc :)

**Closed by dargmuesli** 2022-10-25 20:26 UTC
Labels: bug
